language: node_js
node_js:
  - '5'

addons:
  firefox: '43.0'

cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache/bower'

env:
  # From the first of 1.2 to the latest of 1.2, 1.3, and 1.4.
  # Since 1.5 introduced a breaking change to ngTouch, there will be no such
  # changes to 1.4 as that is now in maintenance only, so we can reliably
  # support whatever the latest of 1.4 is.
  global:
    - DEBUG=true
  matrix:
    - ANGULAR_VERSION=1.2.0
    - ANGULAR_VERSION=1.2
    - ANGULAR_VERSION=1.3
    - ANGULAR_VERSION=1.4

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - npm install codecov.io

script:
  - npm test

after_success:
  - $(npm bin)/codecov < coverage/lcov.info

notifications:
    email: false
