language: node_js
node_js:
  - '5'

addons:
  firefox: '43.0'

cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache/bower'

env:
  - ANGULAR_VERSION=1.2.29
  - ANGULAR_VERSION=1.3.20
  - ANGULAR_VERSION=1.4.9

before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - npm install codecov.io

script:
  - npm test

after_success:
  - $(npm bin)/codecov < coverage/lcov.info

notifications:
    email: false
