language: node_js
node_js:
  - '5'

addons:
  firefox: '43.0'

cache:
  directories:
    - '$HOME/.npm'
    - '$HOME/.cache/bower'

# Test from the first of 1.2 to the latest of 1.2, 1.3, and 1.4.
# Since 1.5 introduced a breaking change to ngTouch, there will be no such
# changes to 1.4 as that is now in maintenance only, therefore we can reliably
# support whatever the latest of 1.4 is.
env:
  matrix:
    # angular-mocks 1.2.11 is the first version to support jasmine2
    # Test more 1.2 versions
    - ANGULAR_VERSION=1.2.0 ANGULAR_MOCKS_VERSION=1.2.11
    - ANGULAR_VERSION=1.2.10 ANGULAR_MOCKS_VERSION=1.2.11
    - ANGULAR_VERSION=1.2.16
    - ANGULAR_VERSION=1.2
    - ANGULAR_VERSION=1.3
    - ANGULAR_VERSION=1.4

# install runs npm install by default
# The postinstall step sets the bower dependencies to the given ANGULAR_VERSION
# and runs bower install
# We need to make sure the right versions were installed, and we can do that in
# before_script which comes after install

before_script:
  - bin/testAngularVersion
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - npm install codecov.io

script:
  - npm test

after_success:
  - $(npm bin)/codecov < coverage/lcov.info

notifications:
    email: false
